import {
  AlertCircle,
  Calendar,
  CalendarCheck,
  CheckCircle,
  XCircle,
} from "lucide-react";

export const statusOptions = [
  {
    value: "scheduled",
    label: "Scheduled",
    color: "text-blue-600 bg-blue-100",
    icon: Calendar,
  },
  {
    value: "confirmed",
    label: "Confirmed",
    color: "text-green-600 bg-green-100",
    icon: CheckCircle,
  },
  {
    value: "in-progress",
    label: "In Progress",
    color: "text-yellow-600 bg-yellow-100",
    icon: AlertCircle,
  },
  {
    value: "completed",
    label: "Completed",
    color: "text-purple-600 bg-purple-100",
    icon: CalendarCheck,
  },
  {
    value: "cancelled",
    label: "Cancelled",
    color: "text-red-600 bg-red-100",
    icon: XCircle,
  },
];

export const technicians = [
  "Suresh Tamang",
  "Anil Gurung",
  "Karim Miya",
  "Rajesh Lama",
  "Binod Chhetri",
];

export const appointmentDetails = [
  {
    id: 1,
    customerName: "Ram Bahadur Shrestha",
    phone: "9841234567",
    email: "ram@email.com",
    deviceType: "Mobile",
    deviceModel: "iPhone 14 Pro",
    issueDescription: "Screen cracked and not responding to touch",
    appointmentDate: "2024-08-15",
    appointmentTime: "10:00",
    status: "scheduled",
    priority: "high",
    assignedTechnician: "Suresh Tamang",
    estimatedCost: "Rs. 15,000",
    notes: "Customer mentioned water damage as well",
    createdAt: "2024-08-10T09:30:00",
  },
  {
    id: 2,
    customerName: "Sunita Paudel",
    phone: "9856789012",
    email: "sunita@email.com",
    deviceType: "Laptop",
    deviceModel: "Dell Inspiron 15",
    issueDescription: "Not booting, shows blue screen error",
    appointmentDate: "2024-08-15",
    appointmentTime: "14:30",
    status: "confirmed",
    priority: "medium",
    assignedTechnician: "Anil Gurung",
    estimatedCost: "Rs. 8,000",
    notes: "Bring charger and any backup drives",
    createdAt: "2024-08-09T14:15:00",
  },
  {
    id: 3,
    customerName: "Manoj Rai",
    phone: "9803456789",
    email: "manoj@email.com",
    deviceType: "TV",
    deviceModel: "Samsung 55 Smart TV",
    issueDescription: "No display, power LED blinking",
    appointmentDate: "2024-08-16",
    appointmentTime: "11:00",
    status: "in-progress",
    priority: "low",
    assignedTechnician: "Karim Miya",
    estimatedCost: "Rs. 12,000",
    notes: "Home service required - Kathmandu area",
    createdAt: "2024-08-08T16:45:00",
  },
  {
    id: 4,
    customerName: "Priya Sharma",
    phone: "9812345678",
    email: "priya@email.com",
    deviceType: "Tablet",
    deviceModel: "iPad Air 5th Gen",
    issueDescription: "Battery draining very fast, will not hold charge",
    appointmentDate: "2024-08-17",
    appointmentTime: "15:30",
    status: "completed",
    priority: "medium",
    assignedTechnician: "Rajesh Lama",
    estimatedCost: "Rs. 6,500",
    notes: "Battery replacement completed successfully",
    createdAt: "2024-08-07T11:20:00",
  },
];
